### ISSUE TITLE
Migration to version 10.0-storage-image

### ISSUE THREAD

**Issue by renatonlima** [akretion/product-attribute#8]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0-storage-image

# Modules to migrate

- [ ] base_custom_attributes
- [ ] customer_context_in_product_view
- [ ] customer_pricing_in_product_view
- [ ] partner_custom_attributes
- [ ] pricelist_item_generator
- [ ] pricelist_per_product
- [ ] product_attribute_multi_type
- [ ] product_attribute_priority
- [ ] product_brand
- [ ] product_catalog_report
- [ ] product_categ_attributes
- [ ] product_code_builder
- [ ] product_code_builder_sequence
- [ ] product_custom_attributes
- [ ] product_custom_info
- [ ] product_customer_code
- [ ] product_dimension
- [ ] product_electronic
- [ ] product_gift
- [ ] product_gtin
- [ ] product_icecat
- [ ] product_index
- [ ] product_listprice_upgrade
- [ ] product_lot_foundry
- [ ] product_m2mcategories
- [ ] product_manufacturer
- [ ] product_multi_image
- [ ] product_multi_price
- [ ] product_pricelist_fixed_price
- [ ] product_prices_on_variant
- [ ] product_profile
- [ ] product_profile_example
- [ ] product_qt
- [ ] product_quick_stock_rule
- [ ] product_search_reference
- [ ] product_sequence
- [ ] product_series
- [ ] product_size
- [ ] product_standard_price_tax_included
- [ ] product_supplierinfo_for_customer
- [ ] product_supplierinfo_tree_price_info
- [ ] product_variant_inactive
- [ ] product_weight
- [ ] production_lot_custom_attributes
